### ISSUE TITLE
Script Error

### ISSUE THREAD

**Issue by rco-titus** [damat/SimpleWatermark#2]
I keep getting a error when i try to use the watermark, it keeps saying "ScriptError: you need authorization to preform that action"

**Comment by damat** [comment]
Could you please try to reinstall the add-on? Be sure to provide all requested permissions since this is the only way to make it work

**Comment by damat** [comment]
Closed the issue with no response

**Comment by kevinlopez85** [comment]
I also have the issue, it happens with accounts with editions of G suite, Workspace.
It works correctly on personal accounts.

**Comment by damat** [comment]
> I also have the issue, it happens with accounts with editions of G suite, Workspace.
> It works correctly on personal accounts.

That's the thing: I tried to reproduce this error on my side. I'm using multiple Google accounts: personal, G Suite as admin, G Suite as a user. It works everywhere with no issues or errors. So we simply don't understand the reason and have to idea how to fix it =(

![Proof](https://i.imgur.com/2Kpk9xh.png)

**Comment by kevinlopez85** [comment]
I am from Mexico, the document has the permissions and has been edited, it shows the image message that says ...

ScriptError: Exception: Could not find any item with the specified ID, possibly because you did not edit this item or you do not have permission to access it.

In my personal account it works fine

Do I need to apply any special permission in the G Suite administration console?

![error](https://user-images.githubusercontent.com/11575043/98836746-acf46180-2407-11eb-8091-23bfb9397053.PNG)
